### ISSUE TITLE
Modal Button Overlay

### ISSUE THREAD

**Issue by nerdyninja** [stab-siesgst/stab-website#1]
<img width="428" alt="screen shot 2016-10-30 at 3 36 41 pm" src="https://cloud.githubusercontent.com/assets/20356666/19835822/bf572964-9eb6-11e6-8d41-4e612176e6d1.png">

**Comment by RaajNadar** [comment]
That button is just for testing purpose.. I am making the universal alert box system but the job is not yet completed.
